package net.daisyquest.daisyquestgame.Model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import lombok.Data;

import java.util.List;
import java.util.Map;

@Data
@Document(collection = "status_effects")
public class StatusEffect {
    @Id
    private String id;
    private String displayName;
    private String shortDisplayName;
    private String color;
    private String borderColor;
    private List<StatusEffectPropertyContainer> properties;
    private Map<String, CombatStatusContainer> playerStatuses;
    private String iconPath;

    public StatusEffect(String id, String displayName, String shortDisplayName, String color, String borderColor,
                        List<StatusEffectPropertyContainer> properties, String iconPath) {
        this.id = id;
        this.displayName = displayName;
        this.shortDisplayName = shortDisplayName;
        this.color = color;
        this.borderColor = borderColor;
        this.properties = properties;
        this.iconPath = iconPath;
    }

    // Default constructor
    public StatusEffect() {
        this.color = "lightgray";
        this.borderColor = "darkgray";
    }

    // Getters and setters are automatically generated by Lombok's @Data annotation
}