name: Build and deploy JAR app to Azure Web App

on:
  push:
    branches:
      - dev
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java version
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ github.ref == 'refs/heads/master' && 'Production' || 'Development' }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ github.ref == 'refs/heads/master' && secrets.AZURE_CREDENTIALS || secrets.AZURE_CREDENTIALS_DEV }}

      - name: Check Azure CLI version and account info
        run: |
          az --version
          az account show
          az account list --query "[?isDefault].{Name:name, ID:id, TenantID:tenantId}" -o table

      - name: Check Web App permissions
        run: |
          APP_NAME=${{ github.ref == 'refs/heads/master' && 'DaisyQuest' || 'DaisyQuest-Dev' }}
          RESOURCE_GROUP=${{ github.ref == 'refs/heads/master' && 'DaisyQuest' || 'DaisyQuest-Dev' }}
          az webapp show --name $APP_NAME --resource-group $RESOURCE_GROUP
        continue-on-error: true

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ github.ref == 'refs/heads/master' && 'DaisyQuest' || 'DaisyQuest-Dev' }}
          slot-name: 'Production'
          package: ${{ github.workspace }}/*[!-plain].jar

      - name: Azure Logout
        run: |
          az logout
        if: always()

    env:
      AZURE_CLI_DISABLE_CONNECTION_VERIFICATION: 1